config/routes.rb
Rails.application.routes.draw do
  root "admin/payments#index"
  get 'admin', to: redirect('/admin/payments')
  get '/service-worker.js' => "service_workers#service_worker"
  get '/manifest.json' => "service_workers#manifest"
  get '/offline.html' => "service_workers#offline"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :payments do
      get "summary", on: :collection
    end
    resources :projects
    resources :periodic_payments
    resources :notebooks
    resources :users
    get 'signin', to: 'sessions#new'
    post 'signin', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end
end

app/models/project.rb
class Project < ApplicationRecord
	has_rich_text :note

	has_many :payments
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < AdminController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :set_search

  # GET /projects
  def index
    authorize [:admin, :project], :index?
    # @pagy, @projects = pagy(@q.result(distinct: true).order(updated_at: :desc), items: 20)
    @projects = @q.result(distinct: true).order(updated_at: :desc)
  end

  # GET /projects/1
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    authorize [:admin, @project]
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)
    authorize [:admin, @project]

    if @project.save
      flash[:success] = I18n.t('flash.create_success')
      redirect_to [:admin, @project]
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      flash[:success] = I18n.t('flash.update_success')
      redirect_to [:admin, @project]
    else
      render :edit
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    flash[:success] = I18n.t('flash.destroy_success')
    redirect_to admin_projects_url
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    	authorize [:admin, @project]
    end

    def set_search
      @q = Project.ransack(params[:q])
      @nav_search_symbol = :id_eq
      @nav_search_placeholder = nil
    end

    # Only allow a trusted parameter "white list" through.
    def project_params
      params.require(:project).permit(:name, :note)
    end
end

app/views/admin/projects/_filter.html.erb
<%= search_form_for [:admin, @q] do |f| %>
	<div class="form-row">
    <div class="form-group col-12">
      <%= f.label @nav_search_symbol, I18n.t("text.filter.#{@nav_search_symbol.to_s}") %>
      <%= f.search_field @nav_search_symbol, class: "form-control" %>
    </div>
  </div>
  <%= link_to I18n.t("text.clear"), admin_projects_path, class: "btn btn-link text-danger btn-sm" %>
  <%= f.submit I18n.t("text.apply"), class: "btn btn-secondary float-right btn-sm" %>
<% end %>

app/views/admin/projects/_form.html.erb
<%= form_with model: [:admin, project], local: true, class: "mb-5" do |f| %>
  <div class="row">
    <div class="offset-lg-3 col-lg-6">
      <div class="form-group <%= project.errors[:name].present? ? 'has-danger' : '' %>">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control #{project.errors[:name].present? ? 'is-invalid' : ''}" %>
        <% if project.errors[:name].present? %>
    	    <div class="invalid-feedback">
    	      <%= project.errors[:name].join(", ") %>
    	    </div>
        <% end %>
      </div>

      <div class="form-group <%= project.errors[:note].present? ? 'has-danger' : '' %>">
        <%= f.label :note %>
        <%= f.rich_text_area :note, class: "form-control #{project.errors[:note].present? ? 'is-invalid' : ''}" %>
        <% if project.errors[:note].present? %>
          <div class="invalid-feedback">
            <%= project.errors[:note].join(", ") %>
          </div>
        <% end %>
      </div>
    
      <%= link_to I18n.t('text.cancel'), admin_projects_path, class: "btn btn-link text-danger" %>
      <%= f.submit class: "btn btn-primary float-right" %>
    </div>
  </div>
<% end %>

app/views/admin/projects/_project.html.erb
<div class="col-sm-6 col-md-4 mb-4" id="project-<%= project.id %>">
	<div class="card p-3">
		<div class="list-group list-group-flush">
		  <li class="list-group-item flex-column align-items-start">
		    <div class="d-flex w-100 justify-content-between">
		      <h5 class="mb-1"><%= Project.human_attribute_name("name") %></h5>
		    </div>
		    <p class="mb-1">
		    	<% if project.name.present? %>
	          <%= project.name %>
	        <% else %>
	          <span class="text-muted"><%= I18n.t("text.attr_no_value") %></span>
	        <% end %>
	      </p>
		  </li>
		  <li class="list-group-item flex-column align-items-start">
		    <div class="d-flex w-100 justify-content-between">
		      <h5 class="mb-1"><%= Project.human_attribute_name("note") %></h5>
		    </div>
		    <p class="mb-1">
		    	<% if project.note.present? %>
	          <%= project.note %>
	        <% else %>
	          <span class="text-muted"><%= I18n.t("text.attr_no_value") %></span>
	        <% end %>
	      </p>
		  </li>
		  <li class="list-group-item flex-column align-items-start">
	      <%= link_to I18n.t('text.edit'), edit_admin_project_path(project), class: "btn btn-primary" %>
	      <%= link_to I18n.t('text.destroy'), [:admin, project], method: :delete, data: { confirm: I18n.t("text.confirm_destroy") }, class: "btn btn-danger btn-sm float-right" %>
	    </li>
		</div>
	</div>
</div>

app/views/admin/projects/_projects_table.html.erb
<table class="table table-hover" id="js-projects-tablesort">
	<thead>
		<tr>
			<th><%= Project.human_attribute_name("name") %></th>
			<th><%= Project.human_attribute_name("note") %></th>
		</tr>
	</thead>
	<tbody>
		<% projects.map do |project| %>
			<tr>
				<td><%= project.name %></td>
				<td><%= project.note %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<script type="text/javascript">
	document.addEventListener("DOMContentLoaded", function() {
		new Tablesort(document.getElementById('js-projects-tablesort'), {
	    descending: true
	  });
	})
</script>

app/views/admin/projects/edit.html.erb
<%= link_to admin_projects_path(anchor: "project-#{@project.id}"), class: "btn btn-link" do %>
  &#8592; <%= I18n.t('text.back') %>
<% end %>
<h1 class="h2"><%= I18n.t('text.edit') %><%= Project.model_name.human %></h1>
<%= render "admin/projects/form", project: @project %>

app/views/admin/projects/index.html.erb
<h1 class="h2">
  <%= Project.model_name.human %><%= I18n.t("text.index") %>
  <% unless not_desktop? %>
	  <%= link_to "#projectAdvanceSearch", class: "d-print-none btn btn-link float-right d-none d-lg-inline-block", data: { toggle: "collapse" } do %>
	  	<i class="material-icons">&#xE152;</i>
	  <% end %>
	<% end %>
</h1>

<% unless not_desktop? %>
	<div class="d-print-none mb-4 collapse <%= 'show' if params[:q].present? %>" id="projectAdvanceSearch">
		<div class="card">
			<div class="card-body">
				<%= render "filter" %>
			</div>
		</div>
	</div>
	<div class="mt-2 mb-4 text-right <%= 'd-none' unless params[:q].present? %>">
		<%= I18n.t("text.search_result") %>：<%= @projects.size %>
	</div>
<% end %>

<%#== pagy_bootstrap_nav(@pagy) %>
<div class="row">
	<% if not_desktop? %>
  	<%= render @projects %>
  <% else %>
  	<%= render partial: "projects_table", locals: { projects: @projects } %>
  <% end %>
</div>
<%#== pagy_bootstrap_nav(@pagy) %>

<div class="btn-abs-wrapper">
	<%= link_to new_admin_project_path, class: "btn btn-success btn-icon--circle" do %>
		<i class="material-icons">&#xE145;</i>
	<% end %>
	<% if not_desktop? %>
		<%= link_to "#", class: "btn btn-secondary d-lg-none btn-icon--circle", data: { toggle: "modal", target: "#searchModal" } do %>
	    <i class="material-icons">&#xE8B6;</i>
	  <% end %>
  <% end %>
</div>

<% if not_desktop? %>
  <%= render "admin/common/search_modal" %>
<% end %>

app/views/admin/projects/new.html.erb
<%= link_to admin_projects_path, class: "btn btn-link" do %>
  &#8592; <%= I18n.t('text.back') %>
<% end %>
<h1 class="h2"><%= I18n.t('text.new') %><%= Project.model_name.human %></h1>
<%= render "admin/projects/form", project: @project %>

app/views/admin/projects/show.html.erb
<%= link_to admin_projects_path(anchor: "project-#{@project.id}"), class: "btn btn-link" do %>
  &#8592; <%= I18n.t('text.back') %>
<% end %>
<div class="row">
  <div class="col-lg-9">
  	<div class="row">
			<%= render @project %>
		</div>
	</div>
</div>