config/routes.rb
Rails.application.routes.draw do
  root "admin/payments#index"
  get 'admin', to: redirect('/admin/payments')
  get '/service-worker.js' => "service_workers#service_worker"
  get '/manifest.json' => "service_workers#manifest"
  get '/offline.html' => "service_workers#offline"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :payments do
      get "summary", on: :collection
    end
    resources :projects
    resources :periodic_payments
    resources :notebooks
    resources :users
    get 'signin', to: 'sessions#new'
    post 'signin', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end
end

app/models/periodic_payment.rb
class PeriodicPayment < ApplicationRecord
	validates :total, presence: true
	has_rich_text :note

	has_many :payments
end

app/controllers/admin/periodic_payments_controller.rb
class Admin::PeriodicPaymentsController < AdminController
  before_action :set_periodic_payment, only: [:show, :edit, :update, :destroy]
  before_action :set_search

  # GET /periodic_payments
  def index
    authorize [:admin, :periodic_payment], :index?
    # @pagy, @periodic_payments = pagy(@q.result(distinct: true).order(updated_at: :desc), items: 20)
    @periodic_payments = @q.result(distinct: true).order(updated_at: :desc)
  end

  # GET /periodic_payments/1
  def show
  end

  # GET /periodic_payments/new
  def new
    @periodic_payment = PeriodicPayment.new
    authorize [:admin, @periodic_payment]
  end

  # GET /periodic_payments/1/edit
  def edit
  end

  # POST /periodic_payments
  def create
    @periodic_payment = PeriodicPayment.new(periodic_payment_params)
    authorize [:admin, @periodic_payment]

    if @periodic_payment.save
      flash[:success] = I18n.t('flash.create_success')
      redirect_to [:admin, @periodic_payment]
    else
      render :new
    end
  end

  # PATCH/PUT /periodic_payments/1
  def update
    if @periodic_payment.update(periodic_payment_params)
      flash[:success] = I18n.t('flash.update_success')
      redirect_to [:admin, @periodic_payment]
    else
      render :edit
    end
  end

  # DELETE /periodic_payments/1
  def destroy
    @periodic_payment.destroy
    flash[:success] = I18n.t('flash.destroy_success')
    redirect_to admin_periodic_payments_url
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_periodic_payment
      @periodic_payment = PeriodicPayment.find(params[:id])
    	authorize [:admin, @periodic_payment]
    end

    def set_search
      @q = PeriodicPayment.ransack(params[:q])
      @nav_search_symbol = :id_eq
      @nav_search_placeholder = nil
    end

    # Only allow a trusted parameter "white list" through.
    def periodic_payment_params
      params.require(:periodic_payment).permit(:total, :scheduled_day, :note)
    end
end

app/views/admin/periodic_payments/_filter.html.erb
<%= search_form_for [:admin, @q] do |f| %>
	<div class="form-row">
    <div class="form-group col-12">
      <%= f.label @nav_search_symbol, I18n.t("text.filter.#{@nav_search_symbol.to_s}") %>
      <%= f.search_field @nav_search_symbol, class: "form-control" %>
    </div>
  </div>
  <%= link_to I18n.t("text.clear"), admin_periodic_payments_path, class: "btn btn-link text-danger btn-sm" %>
  <%= f.submit I18n.t("text.apply"), class: "btn btn-secondary float-right btn-sm" %>
<% end %>

app/views/admin/periodic_payments/_form.html.erb
<%= form_with model: [:admin, periodic_payment], local: true, class: "mb-5" do |f| %>
  <div class="row">
    <div class="offset-lg-3 col-lg-6">
      <div class="form-group <%= periodic_payment.errors[:total].present? ? 'has-danger' : '' %>">
        <%= f.label :total %>
        <%= f.number_field :total, autofocus: true, pattern: "[0-9]*", required: true, class: "form-control #{periodic_payment.errors[:total].present? ? 'is-invalid' : ''}" %>
        <% if periodic_payment.errors[:total].present? %>
    	    <div class="invalid-feedback">
    	      <%= periodic_payment.errors[:total].join(", ") %>
    	    </div>
        <% end %>
      </div>
    
      <div class="form-group <%= periodic_payment.errors[:scheduled_day].present? ? 'has-danger' : '' %>">
        <%= f.label :scheduled_day %>
        <%= f.number_field :scheduled_day, class: "form-control #{periodic_payment.errors[:scheduled_day].present? ? 'is-invalid' : ''}", placeholder: "每月 5 號就填 5，月底請填 30", min: 1, max: 30 %>
        <% if periodic_payment.errors[:scheduled_day].present? %>
    	    <div class="invalid-feedback">
    	      <%= periodic_payment.errors[:scheduled_day].join(", ") %>
    	    </div>
        <% end %>
      </div>

      <div class="form-group <%= periodic_payment.errors[:note].present? ? 'has-danger' : '' %>">
        <%= f.label :note %>
        <%= f.rich_text_area :note, class: "form-control #{periodic_payment.errors[:note].present? ? 'is-invalid' : ''}" %>
        <% if periodic_payment.errors[:note].present? %>
          <div class="invalid-feedback">
            <%= periodic_payment.errors[:note].join(", ") %>
          </div>
        <% end %>
      </div>
    
      <%= link_to I18n.t('text.cancel'), admin_periodic_payments_path, class: "btn btn-link text-danger" %>
      <%= f.submit class: "btn btn-primary float-right" %>
    </div>
  </div>
<% end %>

app/views/admin/periodic_payments/_periodic_payment.html.erb
<div class="col-sm-6 col-md-4 mb-4" id="periodic_payment-<%= periodic_payment.id %>">
	<div class="card p-3">
		<div class="list-group list-group-flush">
		  <li class="list-group-item flex-column align-items-start">
		    <div class="d-flex w-100 justify-content-between">
		      <h5 class="mb-1"><%= PeriodicPayment.human_attribute_name("total") %></h5>
		    </div>
		    <p class="mb-1">
		    	<% if periodic_payment.total.present? %>
	          <%= periodic_payment.total %>
	        <% else %>
	          <span class="text-muted"><%= I18n.t("text.attr_no_value") %></span>
	        <% end %>
	      </p>
		  </li>
		  <li class="list-group-item flex-column align-items-start">
		    <div class="d-flex w-100 justify-content-between">
		      <h5 class="mb-1"><%= PeriodicPayment.human_attribute_name("scheduled_day") %></h5>
		    </div>
		    <p class="mb-1">
		    	<% if periodic_payment.scheduled_day.present? %>
	          <%= periodic_payment.scheduled_day %>
	        <% else %>
	          <span class="text-muted"><%= I18n.t("text.attr_no_value") %></span>
	        <% end %>
	      </p>
		  </li>
		  <li class="list-group-item flex-column align-items-start">
		    <div class="d-flex w-100 justify-content-between">
		      <h5 class="mb-1"><%= PeriodicPayment.human_attribute_name("note") %></h5>
		    </div>
		    <p class="mb-1">
		    	<% if periodic_payment.note.present? %>
	          <%= periodic_payment.note %>
	        <% else %>
	          <span class="text-muted"><%= I18n.t("text.attr_no_value") %></span>
	        <% end %>
	      </p>
		  </li>
		  <li class="list-group-item flex-column align-items-start">
	      <%= link_to I18n.t('text.edit'), edit_admin_periodic_payment_path(periodic_payment), class: "btn btn-primary" %>
	      <%= link_to I18n.t('text.destroy'), [:admin, periodic_payment], method: :delete, data: { confirm: I18n.t("text.confirm_destroy") }, class: "btn btn-danger btn-sm float-right" %>
	    </li>
		</div>
	</div>
</div>

app/views/admin/periodic_payments/_periodic_payments_table.html.erb
<table class="table table-hover" id="js-periodic_payments-tablesort">
	<thead>
		<tr>
			<th><%= PeriodicPayment.human_attribute_name("total") %></th>
			<th><%= PeriodicPayment.human_attribute_name("scheduled_day") %></th>
			<th><%= PeriodicPayment.human_attribute_name("note") %></th>
		</tr>
	</thead>
	<tbody>
		<% periodic_payments.map do |periodic_payment| %>
			<tr>
				<td><%= periodic_payment.total %></td>
				<td><%= periodic_payment.scheduled_day %></td>
				<td><%= periodic_payment.note %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<script type="text/javascript">
	document.addEventListener("DOMContentLoaded", function() {
		new Tablesort(document.getElementById('js-periodic_payments-tablesort'), {
	    descending: true
	  });
	})
</script>

app/views/admin/periodic_payments/edit.html.erb
<%= link_to admin_periodic_payments_path(anchor: "periodic_payment-#{@periodic_payment.id}"), class: "btn btn-link" do %>
  &#8592; <%= I18n.t('text.back') %>
<% end %>
<h1 class="h2"><%= I18n.t('text.edit') %><%= PeriodicPayment.model_name.human %></h1>
<%= render "admin/periodic_payments/form", periodic_payment: @periodic_payment %>

app/views/admin/periodic_payments/index.html.erb
<h1 class="h2">
  <%= PeriodicPayment.model_name.human %><%= I18n.t("text.index") %>
  <% unless not_desktop? %>
	  <%= link_to "#periodic_paymentAdvanceSearch", class: "d-print-none btn btn-link float-right d-none d-lg-inline-block", data: { toggle: "collapse" } do %>
	  	<i class="material-icons">&#xE152;</i>
	  <% end %>
	<% end %>
</h1>

<% unless not_desktop? %>
	<div class="d-print-none mb-4 collapse <%= 'show' if params[:q].present? %>" id="periodic_paymentAdvanceSearch">
		<div class="card">
			<div class="card-body">
				<%= render "filter" %>
			</div>
		</div>
	</div>
	<div class="mt-2 mb-4 text-right <%= 'd-none' unless params[:q].present? %>">
		<%= I18n.t("text.search_result") %>：<%= @periodic_payments.size %>
	</div>
<% end %>

<%#== pagy_bootstrap_nav(@pagy) %>
<div class="row">
	<% if not_desktop? %>
  	<%= render @periodic_payments %>
  <% else %>
  	<%= render partial: "periodic_payments_table", locals: { periodic_payments: @periodic_payments } %>
  <% end %>
</div>
<%#== pagy_bootstrap_nav(@pagy) %>

<div class="btn-abs-wrapper">
	<%= link_to new_admin_periodic_payment_path, class: "btn btn-success btn-icon--circle" do %>
		<i class="material-icons">&#xE145;</i>
	<% end %>
	<% if not_desktop? %>
		<%= link_to "#", class: "btn btn-secondary d-lg-none btn-icon--circle", data: { toggle: "modal", target: "#searchModal" } do %>
	    <i class="material-icons">&#xE8B6;</i>
	  <% end %>
  <% end %>
</div>

<% if not_desktop? %>
  <%= render "admin/common/search_modal" %>
<% end %>

app/views/admin/periodic_payments/new.html.erb
<%= link_to admin_periodic_payments_path, class: "btn btn-link" do %>
  &#8592; <%= I18n.t('text.back') %>
<% end %>
<h1 class="h2"><%= I18n.t('text.new') %><%= PeriodicPayment.model_name.human %></h1>
<%= render "admin/periodic_payments/form", periodic_payment: @periodic_payment %>

app/views/admin/periodic_payments/show.html.erb
<%= link_to admin_periodic_payments_path(anchor: "periodic_payment-#{@periodic_payment.id}"), class: "btn btn-link" do %>
  &#8592; <%= I18n.t('text.back') %>
<% end %>
<div class="row">
  <div class="col-lg-9">
  	<div class="row">
			<%= render @periodic_payment %>
		</div>
	</div>
</div>