config/routes.rb
Rails.application.routes.draw do
  root "admin/payments#index"
  get 'admin', to: redirect('/admin/payments')
  get '/service-worker.js' => "service_workers#service_worker"
  get '/manifest.json' => "service_workers#manifest"
  get '/offline.html' => "service_workers#offline"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :payments do
      get "summary", on: :collection
    end
    resources :projects
    resources :periodic_payments
    resources :notebooks
    resources :users
    get 'signin', to: 'sessions#new'
    post 'signin', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end
end

app/models/user.rb
class User < ApplicationRecord
	enum role: { admin: 0 }
	validates :name, presence: true, uniqueness: true
	has_secure_password
	has_many :payments
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_search

  # GET /users
  def index
    authorize [:admin, :user], :index?
    # @pagy, @users = pagy(@q.result(distinct: true).order(updated_at: :desc), items: 20)
    @users = @q.result(distinct: true).order(updated_at: :desc)
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    authorize [:admin, @user]
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    authorize [:admin, @user]

    if @user.save
      flash[:success] = I18n.t('flash.create_success')
      redirect_to [:admin, @user]
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      flash[:success] = I18n.t('flash.update_success')
      redirect_to [:admin, @user]
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    flash[:success] = I18n.t('flash.destroy_success')
    redirect_to admin_users_url
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    	authorize [:admin, @user]
    end

    def set_search
      @q = User.ransack(params[:q])
      @nav_search_symbol = :id_eq
      @nav_search_placeholder = nil
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :role, :password, :password_confirmation)
    end
end

app/views/admin/users/_filter.html.erb
<%= search_form_for [:admin, @q] do |f| %>
	<div class="form-row">
    <div class="form-group col-12">
      <%= f.label @nav_search_symbol, I18n.t("text.filter.#{@nav_search_symbol.to_s}") %>
      <%= f.search_field @nav_search_symbol, class: "form-control" %>
    </div>
  </div>
  <%= link_to I18n.t("text.clear"), admin_users_path, class: "btn btn-link text-danger btn-sm" %>
  <%= f.submit I18n.t("text.apply"), class: "btn btn-secondary float-right btn-sm" %>
<% end %>

app/views/admin/users/_form.html.erb
<%= form_with model: [:admin, user], local: true, class: "mb-5" do |f| %>
  <div class="row">
    <div class="offset-lg-3 col-lg-6">
      <div class="form-group <%= user.errors[:name].present? ? 'has-danger' : '' %>">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control #{user.errors[:name].present? ? 'is-invalid' : ''}" %>
        <% if user.errors[:name].present? %>
    	    <div class="invalid-feedback">
    	      <%= user.errors[:name].join(", ") %>
    	    </div>
        <% end %>
      </div>
    
      <div class="d-none form-group <%= user.errors[:role].present? ? 'has-danger' : '' %>">
        <%= f.label :role %>
        <%= f.select :role, User.roles.keys, {}, class: "form-control #{user.errors[:role].present? ? 'is-invalid' : ''}" %>
        <% if user.errors[:role].present? %>
    	    <div class="invalid-feedback">
    	      <%= user.errors[:role].join(", ") %>
    	    </div>
        <% end %>
      </div>
    
      <div class="form-group <%= user.errors[:password].present? ? 'has-danger' : '' %>">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control #{user.errors[:password].present? ? 'is-invalid' : ''}" %>
        <% if user.errors[:password].present? %>
    	    <div class="invalid-feedback">
    	      <%= user.errors[:password].join(", ") %>
    	    </div>
        <% end %>
      </div>
    
      <div class="form-group <%= user.errors[:password_confirmation].present? ? 'has-danger' : '' %>">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control #{user.errors[:password_confirmation].present? ? 'is-invalid' : ''}" %>
        <% if user.errors[:password_confirmation].present? %>
    	    <div class="invalid-feedback">
    	      <%= user.errors[:password_confirmation].join(", ") %>
    	    </div>
        <% end %>
      </div>
    
      <%= link_to I18n.t('text.cancel'), admin_users_path, class: "btn btn-link text-danger" %>
      <%= f.submit class: "btn btn-primary float-right" %>
    </div>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<div class="col-sm-6 col-md-4 mb-4" id="user-<%= user.id %>">
	<div class="card p-3">
		<div class="list-group list-group-flush">
		  <li class="list-group-item flex-column align-items-start">
		    <div class="d-flex w-100 justify-content-between">
		      <h5 class="mb-1"><%= User.human_attribute_name("name") %></h5>
		    </div>
		    <p class="mb-1">
		    	<% if user.name.present? %>
	          <%= user.name %>
	        <% else %>
	          <span class="text-muted"><%= I18n.t("text.attr_no_value") %></span>
	        <% end %>
	      </p>
		  </li>
		  <li class="list-group-item flex-column align-items-start">
		    <div class="d-flex w-100 justify-content-between">
		      <h5 class="mb-1"><%= User.human_attribute_name("role") %></h5>
		    </div>
		    <p class="mb-1">
		    	<% if user.role.present? %>
	          <%= user.role %>
	        <% else %>
	          <span class="text-muted"><%= I18n.t("text.attr_no_value") %></span>
	        <% end %>
	      </p>
		  </li>
		  <li class="list-group-item flex-column align-items-start">
	      <%= link_to I18n.t('text.edit'), edit_admin_user_path(user), class: "btn btn-primary" %>
	      <%= link_to I18n.t('text.destroy'), [:admin, user], method: :delete, data: { confirm: I18n.t("text.confirm_destroy") }, class: "btn btn-danger btn-sm float-right" %>
	    </li>
		</div>
	</div>
</div>

app/views/admin/users/_users_table.html.erb
<table class="table table-hover" id="js-users-tablesort">
	<thead>
		<tr>
			<th><%= User.human_attribute_name("name") %></th>
			<th><%= User.human_attribute_name("role") %></th>
		</tr>
	</thead>
	<tbody>
		<% users.map do |user| %>
			<tr>
				<td><%= user.name %></td>
				<td><%= user.role %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<script type="text/javascript">
	document.addEventListener("DOMContentLoaded", function() {
		new Tablesort(document.getElementById('js-users-tablesort'), {
	    descending: true
	  });
	})
</script>

app/views/admin/users/edit.html.erb
<%= link_to admin_users_path(anchor: "user-#{@user.id}"), class: "btn btn-link" do %>
  &#8592; <%= I18n.t('text.back') %>
<% end %>
<h1 class="h2"><%= I18n.t('text.edit') %><%= User.model_name.human %></h1>
<%= render "admin/users/form", user: @user %>

app/views/admin/users/index.html.erb
<h1 class="h2">
  <%= User.model_name.human %><%= I18n.t("text.index") %>
  <% unless not_desktop? %>
	  <%= link_to "#userAdvanceSearch", class: "d-print-none btn btn-link float-right d-none d-lg-inline-block", data: { toggle: "collapse" } do %>
	  	<i class="material-icons">&#xE152;</i>
	  <% end %>
	<% end %>
</h1>

<% unless not_desktop? %>
	<div class="d-print-none mb-4 collapse <%= 'show' if params[:q].present? %>" id="userAdvanceSearch">
		<div class="card">
			<div class="card-body">
				<%= render "filter" %>
			</div>
		</div>
	</div>
	<div class="mt-2 mb-4 text-right <%= 'd-none' unless params[:q].present? %>">
		<%= I18n.t("text.search_result") %>：<%= @users.size %>
	</div>
<% end %>

<%#== pagy_bootstrap_nav(@pagy) %>
<div class="row">
	<% if not_desktop? %>
  	<%= render @users %>
  <% else %>
  	<%= render partial: "users_table", locals: { users: @users } %>
  <% end %>
</div>
<%#== pagy_bootstrap_nav(@pagy) %>

<div class="btn-abs-wrapper">
	<%= link_to new_admin_user_path, class: "btn btn-success btn-icon--circle" do %>
		<i class="material-icons">&#xE145;</i>
	<% end %>
	<% if not_desktop? %>
		<%= link_to "#", class: "btn btn-secondary d-lg-none btn-icon--circle", data: { toggle: "modal", target: "#searchModal" } do %>
	    <i class="material-icons">&#xE8B6;</i>
	  <% end %>
  <% end %>
</div>

<% if not_desktop? %>
  <%= render "admin/common/search_modal" %>
<% end %>

app/views/admin/users/new.html.erb
<%= link_to admin_users_path, class: "btn btn-link" do %>
  &#8592; <%= I18n.t('text.back') %>
<% end %>
<h1 class="h2"><%= I18n.t('text.new') %><%= User.model_name.human %></h1>
<%= render "admin/users/form", user: @user %>

app/views/admin/users/show.html.erb
<%= link_to admin_users_path(anchor: "user-#{@user.id}"), class: "btn btn-link" do %>
  &#8592; <%= I18n.t('text.back') %>
<% end %>
<div class="row">
  <div class="col-lg-9">
  	<div class="row">
			<%= render @user %>
		</div>
	</div>
</div>